apiVersion: v1
kind: Namespace
metadata:
  name: uid
  labels:
    name: uid
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-high
    namespace: uid
  spec:
    hard:
      request.cpu: "1"
      request.memory: 200Gi
      limits.cpu: "2"
      limits.memory: 300Gi
      pods: "10"