apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configure
data:
  nginx: |
    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
     }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
data:
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo "Hello, World! $DB_HOST $DB_USER" > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-configmap 
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
          - name: DB_HOST 
            valueFrom:
              configMapKeyRef:
                name: vars   
                key: db_host
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: vars   
                key: db_user
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/conf.d
        - name: script-vol
          mountPath: /opt
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx-configure
          items:
            - key: nginx
              path: default.conf
      - name: script-vol
        configMap:
          name: vars
          items:
            - key: script
              path: script.sh
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080