apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
        cpu: "1"
      limits:
        memory: "200Mi"
        cpu: "2"
    command: ["stress"]
    args: 
      - -cpus
      - "3"