apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "120Mi"
        cpu: "500m"
    command: ["stress"]
    args: [ "--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]