apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: dev
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 512Mi
    defaultRequest: # this section defines default requests
      cpu: 400m
      memory: 250Mi
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: dev
  labels:
    app: front
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80