apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on-2
  namespace: ci
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: IfNotPresent
        image: harry2680/backend-k8s-hands-on
---

apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on-2
  namespace: ci
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080