apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: front
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: backend
    env: prod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
